spring.application.name=smart-complaint-system
spring.datasource.url=jdbc:mysql://localhost:3306/civicfix_db
spring.datasource.username=root
spring.datasource.password=laharisql36@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true